### ISSUE TITLE
Fatal Error in the extension ..

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson-Translation-Extension#11]
Hello, 
Some clients and I, we have a PHP fatal error with the Translation Extension : 

```
Fatal error: Call to a member function get_settings() on a non-object in /.../wp-content/plugins/unyson/framework/extensions/translation/extensions/translate-widgets/class-fw-extension-translate-widgets.php on line 200
```

Anyone else ? It happens few hours after the activation, when I activated another plugin.

Thank you,

2F

**Comment by llemurya** [comment]
@2Fwebd can you get me an ftp details at the  dev-team@unyson.io, in order to make some debugging and fix this bug.

**Comment by 2Fwebd** [comment]
I just sent you an email @llemurya ;)

**Comment by llemurya** [comment]
@2Fwebd thanks.Soon it will be fixed.

**Comment by 2Fwebd** [comment]
Thanks ! I hope it's not caused by the theme (but I can't find any relation), we use it only in themes/woffice/inc/hooks.php
with : 

```
elseif(function_exists('fw_ext_translation_get_frontend_active_language') ) { 
        echo '<div id="nav-languages">
        <a href="javascript:void(0)">
            <i class="fa fa-flag"></i>'. esc_html(fw_ext( 'translation' )->get_frontend_active_language()) .' <i class="fa fa-angle-down"></i>
        </a>';
        fw_ext( 'translation' )->frontend_language_switcher();
        echo '</div>';
    }
    // ELSE RETURN NOTHING
    else {
        return;
    }
```

But that's all, I hope that helps. Let me know if I can help ! 

2F

**Comment by 2Fwebd** [comment]
Thanks :)

2F
