### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by aamirs332** [ThemeFuse/Unyson-Translation-Extension#13]
i am using unyson from last 6 month, its awesome, now i have used first time translation extension, sorry to say but now am facing too much problems in translation extension, these are given below,

1:- When add language as English, Arabic,and Farci and after addingh i remove english from it. when i remove then an error is coming as : Notice: Undefined index: en in D:\xampp New\htdocs\www\triathlon\wp-content\plugins\unyson\framework\extensions\translation\class-fw-extension-translation.php on line 492. 
http://prntscr.com/8e9kcc
http://prntscr.com/8e9lj7
![sz94huf](https://cloud.githubusercontent.com/assets/5873187/9754015/f38a5d40-56dd-11e5-8c5a-aa171bd1d23a.png)
![xvr9om4](https://cloud.githubusercontent.com/assets/5873187/9754016/f38aa7e6-56dd-11e5-850a-e0d739eed1fe.png)

2:- Second when i Select any language from front end then nothing happened. 
am using this code to print all languages on front end , is am going on right way?

http://prntscr.com/8e9lzx
![44m7mzw](https://cloud.githubusercontent.com/assets/5873187/9754088/c45f340e-56de-11e5-9420-41d4bb7f690e.png)

<?php 
    if (function_exists('fw_ext_translation_get_frontend_active_language')) {
                cho '<ul class="dropdown-menu languages" aria-labelledby="languages">
            <li><a href="javascript:void(0)">
                <i class="fa fa-flag"></i>' . esc_html(fw_ext('translation')->get_frontend_active_language()) . ' <i class="fa fa-angle-down"></i>
                                        </a></li>';
                                    fw_ext('translation')->frontend_language_switcher();
                                    echo '</ul>';
                                }
                                // ELSE RETURN NOTHING
                                else {
                                    return;
                                }
        ?> 
Please help my asap.

**Comment by llemurya** [comment]
I reproduced the bug, soon I will fix it. This is the [video](https://www.youtube.com/watch?v=hWgZmlXD4B8) how translation works.

**Comment by llemurya** [comment]
@aamirs332 please provide more details why in frontend the language not change,maybe you didn't create translation posts in different languages or you didn't create a menu in different languages,please watch video in the above comment and if not help , please open another issue and describe problem more detailed. Thanks for the feedback. I am waiting for your response.

**Comment by aamirs332** [comment]
Thanks for your kind response , I have see video for translation, actually I was listing all language via code, then I see Video how to use translation. I will inform you if still issue found. Thanks

**Comment by aamirs332** [comment]
When I click On any language from front end nothing happened. I have two languages English and   Deutsch, i am using this code to list all languages,
if (function_exists('fw_ext_translation_get_frontend_active_language')) {
        echo '<ul class="dropdown-menu languages" aria-labelledby="languages">
        <li><a href="javascript:void(0)">
        <i class="fa fa-flag"></i>' . esc_html(fw_ext('translation')->get_frontend_active_language()) . ' <i class="fa fa-angle-down"></i>
            </a></li>';
        fw_ext('translation')->frontend_language_switcher();
        echo '</ul>';
    }

This code display all languages , but the problem is that when click any language nothing happened.how i can use languages while i won't use widget.

![xxt1rea](https://cloud.githubusercontent.com/assets/5873187/9781981/eee576aa-57b2-11e5-9af0-cbaca4ca55a4.png)

How i can use language set. ?

**Comment by llemurya** [comment]
@aamirs332 can you send the ftp details at dev-team@unyson.io in order to inspect this case on the server side. I am waiting for your response.

**Comment by aamirs332** [comment]
hello @llemurya , i have sent you en email, can you please give me some kind of code which can loop all languages added at admin site. and these languages should translate pages.
when i click on language its url should be be like this http://triathlon.themographics.com/sports/?fw_lang=ar

but nothing happened when i click any language. Your language extension like WPML?

**Comment by llemurya** [comment]
@aamirs332 nothing happend because you don't add translation for posts , for pages, for menus, by default if the translation did not exists it redirects to home page.Please test on this page , I added translation to it, change language and the post will change, you use correct the language switcher. http://triathlon.themographics.com/sports/fw_lang/en/2015/09/08/ride-the-bike-in-a-hard-way-9/

**Comment by aamirs332** [comment]
Thanks you very Much @llemurya :+1:  Issue is resolved. Thanks for Quick response and your help.
