### ISSUE TITLE
I am getting this error when I activate the translation extension

### ISSUE THREAD

**Issue by drkrule** [ThemeFuse/Unyson-Translation-Extension#16]
Fatal error: Call to undefined method FW_Extension_Default::get_admin_active_language()

**Comment by drkrule** [comment]
Any recommendation?

**Comment by ghost** [comment]
Which theme are you using?

**Comment by drkrule** [comment]
http://themeforest.net/item/campaign-your-political-wordpress-theme/13185059?s_rank=7

**Comment by ghost** [comment]
Please report this problem to theme author.

Do you get this error when a default WP theme is active?

**Comment by drkrule** [comment]
If I activate it with the normal I got 500 Internal Server Error

**Comment by ghost** [comment]
Please give the complete error message

```
Fatal error: Call to undefined method FW_Extension_Default::get_admin_active_language() in ... (which file?)
```

**Comment by drkrule** [comment]
Fatal error: Call to undefined method FW_Extension_Default::get_admin_active_language() in /nfs/c03/h05/mnt/47162/domains/puertoricoprogress.com/html/wp-content/plugins/unyson/framework/extensions/Unyson-Translation-Extension-master/extensions/translate-widgets/class-fw-extension-translate-widgets.php on line 204

**Comment by ghost** [comment]
Can you give me admin/ftp access to your site so I can inspect the problem? If yes, send the details to `moldcraft[at]email.com`

**Comment by drkrule** [comment]
Sent

**Comment by ghost** [comment]
Fatal error: Call to undefined method FW_Extension_Default::get_admin_active_language() in /nfs/c03/h05/mnt/47162/domains/puertoricoprogress.com/html/wp-content/plugins/unyson/framework/extensions/**Unyson-Translation-Extension-master**/extensions/translate-widgets/class-fw-extension-translate-widgets.php on line 204

Directory name must be `translation`
