### ISSUE TITLE
Termmeta isn't created

### ISSUE THREAD

**Issue by sammael1106** [ThemeFuse/Unyson-Translation-Extension#19]
Hello!

According your code in `class-fw-extension-translate-terms.php` after creating category with translations should be created an entry in the **DB:Termmeta**, where should be contained information about category, something like this:
`term_id: 1, meta_key: translation_lang, meta_value: en`

But, it wasn't created. 
https://prnt.sc/gzuyic
https://prnt.sc/gzuyp0

I'll attach my theme [underscore-exapmle-theme.zip](https://github.com/ThemeFuse/Unyson-Translation-Extension/files/1402619/underscore-exapmle-theme.zip) the Unyson-Translation-Extension(latest version) located inside of it.

Also, I want to mention that similar mechanism of SEO Extension works perfectly.

**Comment by ViorelEremia** [comment]
Hi,
we don't know what to do with extension "Extension Unyson-Translation-Extension" maybe in the feature it will deleted from our repositories, at the moment we don't support it, please use extensions what is added in dashboard unyson page with extensions.

**Comment by sammael1106** [comment]
I need a recommendation, what plugin can I use for translations, and in won't be in conflict with Unyson?

**Comment by ViorelEremia** [comment]
What do you want to do? Multilanguage site or only string translate.

**Comment by ViorelEremia** [comment]
Try polylang it is free, or wpml for money

**Comment by sammael1106** [comment]
@ViorelEremia sincerely thanks to you! Polylang works perfectly!
