### ISSUE TITLE
How to translate string ?

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson-Translation-Extension#2]
Hi
I have tried this extenstion but its quite compicated for me. can you please provide me details how i can translate theme string via this extension. 

It will be great if you provide me little screencast :) 

Thanks for your help

**Comment by llemurya** [comment]
@xperter Translation at the moment translate posts, menus ,widgets in next versions we will add posibility to translate the strings, here is a video demo https://www.youtube.com/watch?v=hWgZmlXD4B8&feature=youtu.be. If this helps please close the issue.

**Comment by xperter** [comment]
I have already check this :)
Great so i will wait for next version.
Thanks
